name: Build and Test

on:
  push:
    branches: [ main ]  # 触发条件：当代码推送到 main 分支时
  pull_request:
    branches: [ main ]  # 触发条件：当有拉取请求合并到 main 分支时

jobs:
  build:

    runs-on: ubuntu-latest  # 在 Ubuntu 最新版本的操作系统上运行

    steps:
    - uses: actions/checkout@v3  # 检出代码库中的代码
    - name: Set up Python 3 # 设置 Python 3.10 环境
      uses: actions/setup-python@v4
      with:
        python-version: 3
    - name: Install dependencies  # 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests  # 运行测试
      run: |
        pip install pytest
        pytest  # 假设你的测试使用 pytest 框架