# Generated by Django 5.0.4 on 2024-06-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='stuinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sName', models.CharField(max_length=20)),
                ('sNo', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('deptName', models.CharField(max_length=20)),
            ],
        ),
    ]
