# Generated by Django 5.0.4 on 2024-06-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_stuinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinfo',
            options={'verbose_name': '书籍名称', 'verbose_name_plural': '书籍信息'},
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='author',
            field=models.CharField(max_length=20, verbose_name='书籍作者'),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='name',
            field=models.CharField(max_length=20, verbose_name='书籍名'),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='price',
            field=models.IntegerField(verbose_name='书籍定价'),
        ),
    ]
